#!/usr/bin/env zsh
INFO_COLOR="blue"
print -P "%F{$INFO_COLOR}INFO: %fuse batcat instead of cat"
print -P "%F{$INFO_COLOR}INFO: %fcopypath # copies current path to buffer"
print -P "%F{$INFO_COLOR}INFO: %fcopybuffer; ctrl-o # copies command currently typed into."
print -P "%F{$INFO_COLOR}INFO: %fcopyfile # copies contents of a file to the buffer"
print -P "%F{$INFO_COLOR}INFO: %fuse ff to get a colorized preview of fzf rather than using grep"
print -P "%F{$INFO_COLOR}INFO: %fctrl t to select files"
print -P "%F{$INFO_COLOR}INFO: %falt c to switch into subdirectory"
print -P "%F{$INFO_COLOR}INFO: %fctrl r to get a great smart search of command history"
print -P "%F{$INFO_COLOR}INFO: %fz <command> to quickly get to common directories"

print -P "%F{$INFO_COLOR}INFO: %f<leader> key: def"
print -P "%F{$INFO_COLOR}INFO: %fleader rn: to rename a variable"
print -P "%F{$INFO_COLOR}INFO: %fleader ca: to code action"
print -P "%F{$INFO_COLOR}INFO: %fleader gd: goto definition"
print -P "%F{$INFO_COLOR}INFO: %fK: documentation pop up"
print -P "%F{$INFO_COLOR}INFO: %f<leader> sf: Format Code"
print -P "%F{blue}INFO: %fdirs -v # list of auto dirs. "
