print -P "%F{blue}INFO: %fdirs -v # list of auto dirs. "
print -P "%F{blue}INFO: %f<leader>ss toggle terminal "
print -P "%F{blue}INFO: %f<leader> ff searches file names "
print -P "%F{blue}INFO: %f<leader> fg searches inside of files "
print -P "%F{blue}INFO: %f<leader> fr recent files "
print -P "%F{blue}INFO: %f<leader> sf auto format doc "
print -P "%F{blue}INFO: %f<leader> nt nerdtree toggle "
print -P "%F{blue}INFO: %fgcc comment in vim.  5gcc comments next 5 lines. "
print -P "%F{blue}INFO: %fin telescope file browser /h for hidden files "
